development:
  adapter: postgresql
  encoding: unicode
  database: pokemon_development
  pool: 5
  username: ubuntu
  
test:
  adapter: postgresql
  encoding: unicode
  database: pokemon_test
  pool: 5
  username: ubuntu